import "@radix-ui/themes/styles.css"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import NavBar from "./NavBar"
import { Container, Theme } from "@radix-ui/themes"
import AuthProvider from "./auth/Provider"
import QueryClientProvider from "./QueryClientProvider"

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <QueryClientProvider>
        <AuthProvider>
          <body className={inter.variable}>
            <Theme accentColor="violet">
              <NavBar />
              <main className="px-6">
                <Container>{children}</Container>
              </main>
            </Theme>
          </body>
        </AuthProvider>
      </QueryClientProvider>
    </html>
  )
}
